version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: user
      MYSQL_USER: exam
      MYSQL_PASSWORD: Gulab1102
      MYSQL_ROOT_PASSWORD: Gulab1102

    
